In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


Step2- Import Dataset

In [2]:
dataset =pd.read_csv('Dataset.csv')

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [5]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [6]:
dataset.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

Step3- Split Independent and Dpendent Variables

In [7]:
x= dataset.iloc[:,:4]

In [8]:
x

R&D Spend  Administration  Marketing Spend       State
0   165349.20       136897.80        471784.10    New York
1   162597.70       151377.59        443898.53  California
2   153441.51       101145.55        407934.54     Florida
3   144372.41       118671.85        383199.62    New York
4   142107.34        91391.77        366168.42     Florida
5   131876.90        99814.71        362861.36    New York
6   134615.46       147198.87        127716.82  California
7   130298.13       145530.06        323876.68     Florida
8   120542.52       148718.95        311613.29    New York
9   123334.88       108679.17        304981.62  California
10  101913.08       110594.11        229160.95     Florida
11  100671.96        91790.61        249744.55  California
12   93863.75       127320.38        249839.44     Florida
13   91992.39       135495.07        252664.93  California
14  119943.24       156547.42        256512.92     Florida
15  114523.61       122616.84        261776.23    New York
16   78013.11       121597.55        264346.06  California
17   94657.16       145077.58        282574.31    New York
18   91749.16       114175.79        294919.57     Florida
19   86419.70       153514.11             0.00    New York
20   76253.86       113867.30        298664.47  California
21   78389.47       153773.43        299737.29    New York
22   73994.56       122782.75        303319.26     Florida
23   67532.53       105751.03        304768.73     Florida
24   77044.01        99281.34        140574.81    New York
25   64664.71       139553.16        137962.62  California
26   75328.87       144135.98        134050.07     Florida
27   72107.60       127864.55        353183.81    New York
28   66051.52       182645.56        118148.20     Florida
29   65605.48       153032.06        107138.38    New York
30   61994.48       115641.28         91131.24     Florida
31   61136.38       152701.92         88218.23    New York
32   63408.86       129219.61         46085.25  California
33   55493.95       103057.49        214634.81     Florida
34   46426.07       157693.92        210797.67  California
35   46014.02        85047.44        205517.64    New York
36   28663.76       127056.21        201126.82     Florida
37   44069.95        51283.14        197029.42  California
38   20229.59        65947.93        185265.10    New York
39   38558.51        82982.09        174999.30  California
40   28754.33       118546.05        172795.67  California
41   27892.92        84710.77        164470.71     Florida
42   23640.93        96189.63        148001.11  California
43   15505.73       127382.30         35534.17    New York
44   22177.74       154806.14         28334.72  California
45    1000.23       124153.04          1903.93    New York
46    1315.46       115816.21        297114.46     Florida
47       0.00       135426.92             0.00  California
48     542.05        51743.15             0.00    New York
49       0.00       116983.80         45173.06  California

In [9]:
type(x)

pandas.core.frame.DataFrame

In [10]:
x= dataset.iloc[:,:4].values #convert from dataframe to numpy array

In [11]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [12]:
x.ndim #mandatory to be in 2 dimesion for Linear Regression

2

In [14]:
type(x)

numpy.ndarray

In [13]:
y= dataset.iloc[:,-1:]

In [15]:
y.shape

(50, 1)

In [17]:
y= dataset.iloc[:,-1:].values

In [18]:
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

Step5-Encode categorical Text Variables

In [19]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [20]:
x[:,3]=lb.fit_transform(x[:,3])

In [21]:
x

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [22]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder(categorical_features=[3])#categorical Features represents which column to be onehot encoded
x=oh.fit_transform(x).toarray()

C:\Users\Unitech001\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Unitech001\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [23]:
x

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [24]:
x=x[:,1:] #Removing Dummy variable (removing the column which is not required .so removing first column)

In [25]:
x

array([[0.0000000e+00, 1.0000000e+00, 1.6534920e+05, 1.3689780e+05,
        4.7178410e+05],
       [0.0000000e+00, 0.0000000e+00, 1.6259770e+05, 1.5137759e+05,
        4.4389853e+05],
       [1.0000000e+00, 0.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05],
       [0.0000000e+00, 1.0000000e+00, 1.4437241e+05, 1.1867185e+05,
        3.8319962e+05],
       [1.0000000e+00, 0.0000000e+00, 1.4210734e+05, 9.1391770e+04,
        3.6616842e+05],
       [0.0000000e+00, 1.0000000e+00, 1.3187690e+05, 9.9814710e+04,
        3.6286136e+05],
       [0.0000000e+00, 0.0000000e+00, 1.3461546e+05, 1.4719887e+05,
        1.2771682e+05],
       [1.0000000e+00, 0.0000000e+00, 1.3029813e+05, 1.4553006e+05,
        3.2387668e+05],
       [0.0000000e+00, 1.0000000e+00, 1.2054252e+05, 1.4871895e+05,
        3.1161329e+05],
       [0.0000000e+00, 0.0000000e+00, 1.2333488e+05, 1.0867917e+05,
        3.0498162e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0191308e+05, 1.1059411e+05,
        2.29

In [26]:
from sklearn.model_selection import train_test_split                #previously cros_validation was used in sklearn
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [27]:
x_test

array([[1.0000000e+00, 0.0000000e+00, 6.6051520e+04, 1.8264556e+05,
        1.1814820e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0067196e+05, 9.1790610e+04,
        2.4974455e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0191308e+05, 1.1059411e+05,
        2.2916095e+05],
       [1.0000000e+00, 0.0000000e+00, 2.7892920e+04, 8.4710770e+04,
        1.6447071e+05],
       [1.0000000e+00, 0.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05],
       [0.0000000e+00, 1.0000000e+00, 7.2107600e+04, 1.2786455e+05,
        3.5318381e+05],
       [0.0000000e+00, 1.0000000e+00, 2.0229590e+04, 6.5947930e+04,
        1.8526510e+05],
       [0.0000000e+00, 1.0000000e+00, 6.1136380e+04, 1.5270192e+05,
        8.8218230e+04],
       [1.0000000e+00, 0.0000000e+00, 7.3994560e+04, 1.2278275e+05,
        3.0331926e+05],
       [1.0000000e+00, 0.0000000e+00, 1.4210734e+05, 9.1391770e+04,
        3.6616842e+05]])

In [28]:
import keras #Building neural network model back end it has tensorflow
from keras.models import Sequential # initializing model
from keras.layers import Dense # used for adding the neural network layers

Using TensorFlow backend.


In [29]:
model=Sequential()#instance

In [30]:
model.add(Dense(input_dim=5,init="random_uniform",activation="relu",output_dim=3)) #input_dim=no of neurons to have in the input layer(no of independent variables),init=adding weights,activation function,output_dim=next hidden layer
#best thing for output_dim is input_dim/2

C:\Users\Unitech001\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=5, activation="relu", units=3, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


Instructions for updating:
Colocations handled automatically by placer.


In [31]:
model.add(Dense(output_dim=3,init="random_uniform",activation="relu"))# adding hidden layer similary like adding weights

C:\Users\Unitech001\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=3, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [32]:
model.add(Dense(output_dim=1,init="random_uniform"))#adding output layer

C:\Users\Unitech001\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


# In compilation we will define loss strategy(mean square error), weights optimsation startegy(batch grad descent,stocastic grad descent),model performance strategy

In [33]:
model.compile(optimizer='adam',loss='mse',metrics=['mse'])#adam=batch gradient descent

In [34]:
model.fit(x_train,y_train,epochs=1000,batch_size=10)#epochs no of iteration 

Instructions for updating:
Use tf.cast instead.
Epoch 1/1000
40/40 [==============================] - 2s 60ms/step - loss: 13615766784.0000 - mean_squared_error: 13615766784.0000
Epoch 2/1000
40/40 [==============================] - 0s 500us/step - loss: 13615635968.0000 - mean_squared_error: 13615635968.0000
Epoch 3/1000
40/40 [==============================] - 0s 375us/step - loss: 13615445760.0000 - mean_squared_error: 13615445760.0000
Epoch 4/1000
40/40 [==============================] - 0s 300us/step - loss: 13614994944.0000 - mean_squared_error: 13614994944.0000
Epoch 5/1000
40/40 [==============================] - 0s 325us/step - loss: 13614285312.0000 - mean_squared_error: 13614285312.0000
Epoch 6/1000
40/40 [==============================] - 0s 400us/step - loss: 13612794624.0000 - mean_squared_error: 13612794624.0000
Epoch 7/1000
40/40 [==============================] - 0s 225us/step - loss: 13610646016.0000 - mean_squared_error: 13610646016.0000
Epoch 8/1000
40/40 [=========

Epoch 123/1000
40/40 [==============================] - 0s 175us/step - loss: 386338176.0000 - mean_squared_error: 386338176.0000
Epoch 124/1000
40/40 [==============================] - 0s 150us/step - loss: 385552732.0000 - mean_squared_error: 385552732.0000
Epoch 125/1000
40/40 [==============================] - 0s 175us/step - loss: 384974960.0000 - mean_squared_error: 384974960.0000
Epoch 126/1000
40/40 [==============================] - 0s 200us/step - loss: 384244136.0000 - mean_squared_error: 384244136.0000
Epoch 127/1000
40/40 [==============================] - 0s 175us/step - loss: 383833808.0000 - mean_squared_error: 383833808.0000
Epoch 128/1000
40/40 [==============================] - 0s 175us/step - loss: 383119848.0000 - mean_squared_error: 383119848.0000
Epoch 129/1000
40/40 [==============================] - 0s 175us/step - loss: 382464228.0000 - mean_squared_error: 382464228.0000
Epoch 130/1000
40/40 [==============================] - 0s 225us/step - loss: 381907084.00

40/40 [==============================] - 0s 200us/step - loss: 348263876.0000 - mean_squared_error: 348263876.0000
Epoch 187/1000
40/40 [==============================] - 0s 200us/step - loss: 347788156.0000 - mean_squared_error: 347788156.0000
Epoch 188/1000
40/40 [==============================] - 0s 150us/step - loss: 347224892.0000 - mean_squared_error: 347224892.0000
Epoch 189/1000
40/40 [==============================] - 0s 150us/step - loss: 346659484.0000 - mean_squared_error: 346659484.0000
Epoch 190/1000
40/40 [==============================] - 0s 150us/step - loss: 345915636.0000 - mean_squared_error: 345915636.0000
Epoch 191/1000
40/40 [==============================] - 0s 175us/step - loss: 345860636.0000 - mean_squared_error: 345860636.0000
Epoch 192/1000
40/40 [==============================] - 0s 250us/step - loss: 344620768.0000 - mean_squared_error: 344620768.0000
Epoch 193/1000
40/40 [==============================] - 0s 200us/step - loss: 344093192.0000 - mean_squar

40/40 [==============================] - 0s 250us/step - loss: 276347460.0000 - mean_squared_error: 276347460.0000
Epoch 313/1000
40/40 [==============================] - 0s 175us/step - loss: 275641144.0000 - mean_squared_error: 275641144.0000
Epoch 314/1000
40/40 [==============================] - 0s 150us/step - loss: 274937864.0000 - mean_squared_error: 274937864.0000
Epoch 315/1000
40/40 [==============================] - 0s 150us/step - loss: 274485144.0000 - mean_squared_error: 274485144.0000
Epoch 316/1000
40/40 [==============================] - 0s 175us/step - loss: 274129238.0000 - mean_squared_error: 274129238.0000
Epoch 317/1000
40/40 [==============================] - 0s 175us/step - loss: 273729072.0000 - mean_squared_error: 273729072.0000
Epoch 318/1000
40/40 [==============================] - 0s 175us/step - loss: 272895476.0000 - mean_squared_error: 272895476.0000
Epoch 319/1000
40/40 [==============================] - 0s 175us/step - loss: 272678296.0000 - mean_squar

40/40 [==============================] - 0s 175us/step - loss: 220780980.0000 - mean_squared_error: 220780980.0000
Epoch 438/1000
40/40 [==============================] - 0s 175us/step - loss: 220445602.0000 - mean_squared_error: 220445602.0000
Epoch 439/1000
40/40 [==============================] - 0s 175us/step - loss: 219833854.0000 - mean_squared_error: 219833854.0000
Epoch 440/1000
40/40 [==============================] - 0s 150us/step - loss: 219638982.0000 - mean_squared_error: 219638982.0000
Epoch 441/1000
40/40 [==============================] - 0s 175us/step - loss: 219205222.0000 - mean_squared_error: 219205222.0000
Epoch 442/1000
40/40 [==============================] - 0s 150us/step - loss: 218769644.0000 - mean_squared_error: 218769644.0000
Epoch 443/1000
40/40 [==============================] - 0s 225us/step - loss: 218558816.0000 - mean_squared_error: 218558816.0000
Epoch 444/1000
40/40 [==============================] - 0s 225us/step - loss: 218232612.0000 - mean_squar

40/40 [==============================] - 0s 200us/step - loss: 184574632.0000 - mean_squared_error: 184574632.0000
Epoch 563/1000
40/40 [==============================] - 0s 175us/step - loss: 183964364.0000 - mean_squared_error: 183964364.0000
Epoch 564/1000
40/40 [==============================] - 0s 175us/step - loss: 183771282.0000 - mean_squared_error: 183771282.0000
Epoch 565/1000
40/40 [==============================] - 0s 200us/step - loss: 183512644.0000 - mean_squared_error: 183512644.0000
Epoch 566/1000
40/40 [==============================] - 0s 250us/step - loss: 183603872.0000 - mean_squared_error: 183603872.0000
Epoch 567/1000
40/40 [==============================] - 0s 200us/step - loss: 183194768.0000 - mean_squared_error: 183194768.0000
Epoch 568/1000
40/40 [==============================] - 0s 150us/step - loss: 182955888.0000 - mean_squared_error: 182955888.0000
Epoch 569/1000
40/40 [==============================] - 0s 175us/step - loss: 182929329.0000 - mean_squar

40/40 [==============================] - 0s 150us/step - loss: 163378032.0000 - mean_squared_error: 163378032.0000
Epoch 688/1000
40/40 [==============================] - 0s 225us/step - loss: 163187206.0000 - mean_squared_error: 163187206.0000
Epoch 689/1000
40/40 [==============================] - 0s 175us/step - loss: 163094387.0000 - mean_squared_error: 163094387.0000
Epoch 690/1000
40/40 [==============================] - 0s 200us/step - loss: 163072184.0000 - mean_squared_error: 163072184.0000
Epoch 691/1000
40/40 [==============================] - 0s 175us/step - loss: 162903122.0000 - mean_squared_error: 162903122.0000
Epoch 692/1000
40/40 [==============================] - 0s 150us/step - loss: 162797738.0000 - mean_squared_error: 162797738.0000
Epoch 693/1000
40/40 [==============================] - 0s 150us/step - loss: 162686200.0000 - mean_squared_error: 162686200.0000
Epoch 694/1000
40/40 [==============================] - 0s 175us/step - loss: 162523666.0000 - mean_squar

40/40 [==============================] - 0s 150us/step - loss: 153425270.0000 - mean_squared_error: 153425270.0000
Epoch 814/1000
40/40 [==============================] - 0s 175us/step - loss: 153513624.0000 - mean_squared_error: 153513624.0000
Epoch 815/1000
40/40 [==============================] - 0s 225us/step - loss: 153629632.0000 - mean_squared_error: 153629632.0000
Epoch 816/1000
40/40 [==============================] - 0s 175us/step - loss: 153491540.0000 - mean_squared_error: 153491540.0000
Epoch 817/1000
40/40 [==============================] - 0s 200us/step - loss: 153248820.0000 - mean_squared_error: 153248820.0000
Epoch 818/1000
40/40 [==============================] - 0s 150us/step - loss: 153350550.0000 - mean_squared_error: 153350550.0000
Epoch 819/1000
40/40 [==============================] - 0s 200us/step - loss: 153238696.0000 - mean_squared_error: 153238696.0000
Epoch 820/1000
40/40 [==============================] - 0s 175us/step - loss: 153260304.0000 - mean_squar

40/40 [==============================] - 0s 150us/step - loss: 150055600.0000 - mean_squared_error: 150055600.0000
Epoch 939/1000
40/40 [==============================] - 0s 175us/step - loss: 150265370.0000 - mean_squared_error: 150265370.0000
Epoch 940/1000
40/40 [==============================] - 0s 200us/step - loss: 150831539.0000 - mean_squared_error: 150831539.0000
Epoch 941/1000
40/40 [==============================] - 0s 200us/step - loss: 150059220.0000 - mean_squared_error: 150059220.0000
Epoch 942/1000
40/40 [==============================] - 0s 150us/step - loss: 150194968.0000 - mean_squared_error: 150194968.0000
Epoch 943/1000
40/40 [==============================] - 0s 150us/step - loss: 150162140.0000 - mean_squared_error: 150162140.0000
Epoch 944/1000
40/40 [==============================] - 0s 175us/step - loss: 150208136.0000 - mean_squared_error: 150208136.0000
Epoch 945/1000
40/40 [==============================] - 0s 150us/step - loss: 150026932.0000 - mean_squar

In [35]:
x_test

array([[1.0000000e+00, 0.0000000e+00, 6.6051520e+04, 1.8264556e+05,
        1.1814820e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0067196e+05, 9.1790610e+04,
        2.4974455e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0191308e+05, 1.1059411e+05,
        2.2916095e+05],
       [1.0000000e+00, 0.0000000e+00, 2.7892920e+04, 8.4710770e+04,
        1.6447071e+05],
       [1.0000000e+00, 0.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05],
       [0.0000000e+00, 1.0000000e+00, 7.2107600e+04, 1.2786455e+05,
        3.5318381e+05],
       [0.0000000e+00, 1.0000000e+00, 2.0229590e+04, 6.5947930e+04,
        1.8526510e+05],
       [0.0000000e+00, 1.0000000e+00, 6.1136380e+04, 1.5270192e+05,
        8.8218230e+04],
       [1.0000000e+00, 0.0000000e+00, 7.3994560e+04, 1.2278275e+05,
        3.0331926e+05],
       [1.0000000e+00, 0.0000000e+00, 1.4210734e+05, 9.1391770e+04,
        3.6616842e+05]])

In [34]:
model.predict(x_test)

array([[118883.016],
       [120288.72 ],
       [126280.94 ],
       [ 61339.824],
       [171632.34 ],
       [121005.3  ],
       [ 50953.23 ],
       [102690.91 ],
       [116826.91 ],
       [157288.6  ]], dtype=float32)

In [35]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [36]:
model.predict(np.array([[0,1,123456,189900,10098900]]))

array([[925292.44]], dtype=float32)